### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by khalilmansouri** [dzcode-io/dzcode.io#237] opened 2020-11-05 10:07 UTC
Adding locals to the platform, would a great idea in order to address deferent audience with deferent languages,  ex : French / Arabic

**Comment by ZibanPirate** [comment] 2020-11-06 07:31
thank you @khalilmansouri for your suggestions, this feature will be implemented in the near future, you can keep tracking it on #24 , and let us know if you think you can help on this

**Comment by ZibanPirate** [comment] 2021-02-18 09:11
closing as duplicate of #24

**Closed by ZibanPirate** 2021-02-18 09:11 UTC
Labels: duplicate, enhancement
